{
 "title": "Minitwit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Average Requests over time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[$__interval]))",
     "legendFormat": "Average requests over time"
    }
   ]
  },
  {
   "title": "Amount of registered users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Id\")\nFROM \"AspNetUsers\""
    }
   ]
  },
  {
   "title": "Amount of posted twits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Id\") FROM \"Messages\""
    }
   ]
  },
  {
   "title": "Average response time for each action",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action)(http_request_duration_seconds_sum) / sum by (controller, action) (http_request_duration_seconds_count)",
     "legendFormat": "{{action}}@{{controller}}"
    }
   ]
  },
  {
   "title": "Requests per route over time",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total[$__interval])",
     "legendFormat": "{{method}}: {{action}}@{{controller}} -> {{code}} - {{instance}}"
    }
   ]
  }
 ]
}